apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: AuthServer
metadata:
  name: appsso-where-for-dinner
  namespace: my-apps
  labels:
    name: appsso-where-for-dinner
    app: where-for-dinner
  annotations:
    sso.apps.tanzu.vmware.com/allow-client-namespaces: '*'
    sso.apps.tanzu.vmware.com/allow-unsafe-identity-provider: ""
    sso.apps.tanzu.vmware.com/allow-unsafe-issuer-uri: ""
spec:
  tls:
    disabled: true
  tokenSignature:
    signAndVerifyKeyRef:
      name: appsso-where-for-dinner-signing-key
  identityProviders:
  - name: dev-users
    internalUnsafe:
      users:
      - username: where-for-dinner
        password: letseat
        roles:
        - patron
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: appsso-where-for-dinner-signing-key
  namespace: my-apps
spec:
  secretTemplate:
    type: Opaque
    stringData:
      key.pem: $(privateKey)
      pub.pem: $(publicKey)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: where-for-dinner-client-registration-app-operator-reader
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups:
  - sso.apps.tanzu.vmware.com
  resources:
  - ClientRegistration
  verbs:
  - get
  - list
  - watch
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: clientreg-where-for-dinner
spec:
  description:
    short: Where For Dinner AppSSO Client Registrations
  pool:
    group: sso.apps.tanzu.vmware.com
    kind: ClientRegistration
    labelSelector:
      matchLabels:
        services.apps.tanzu.vmware.com/class: clientreg-where-for-dinner
